### PR TITLE
added sage code in comments under each figure; svgs inside PR comments

### PR DESCRIPTION
**Pull request by cg2wilson**
Here are the svgs:
LT1-figure1
LT1-figure2
LT1-figure3
LT1-figure4
LT1-figure5

### CODE REVIEW

**Comment by cg2wilson** [comment]
i pushed this from codespaces and i can't figure out how to retroactively make this a draft PR, i'm sorry..

**Review by jford1906 — APPROVED** [review]

**Comment by StevenClontz** [comment]
Before we approve and merge, @cg2wilson should implement these sageplots (so they'll appear in a full build) and mark the PR as ready for review.

**Comment by siwelwerd** [comment]
Looks good!  Two small suggestions:

1. Use `aspect_ratio=1` as a few of them appear stretched horizontally
2. They might be a bit cleaner with fewer gridlines.  Particularly the step function one.

**Comment by jford1906** [comment]
It says I marked it as ready, but that wasn't intentional. I was trying to figure out how to make suggested changes. Things to go over at the meeting in an hour!

**Review by jford1906 — APPROVED** [review]

**Comment by jford1906** [comment]
These look good to me. I can't seem to get CodeChat to show me a preview in a Codespace, but don't see any issue with merging.

**Comment by StevenClontz** [comment]
I'm confirming the images build now (and will take care of that settings.json conflict).

**Review by StevenClontz — APPROVED** [review]
Made a few minor tweaks. Thanks for this awesome effort!

**Pull request merged**
