### PR TITLE
Clean up and expand IN2

### PR DESCRIPTION
**Pull request by daverosoff**
Addresses #53. I need some help with the text label size in the figure.

### CODE REVIEW

**Comment by StevenClontz** [comment]
(don't forget to mark your PRs as "ready for review" when they're ready)

**Comment by StevenClontz** [comment]
What's the relationship between this and https://github.com/TeamBasedInquiryLearning/library/pull/85 ?

**Comment by daverosoff** [comment]
I don't think there is any. They were separate issues.

**Comment by StevenClontz** [comment]
Then there's something weird with the branches: I see commit `be0a5ed` `Add multiple choice and diagram to "The Box"` showing up both here and there.

**Comment by StevenClontz** [comment]
These branches both include at least one commit in common that's not in `main` yet, so we need to merge them both together first, then review both PRs as a merged PR. Or you might be able to pull off a `git revert` to remove the changes from commits that aren't intended to be a part of a PR.

**Comment by daverosoff** [comment]
OK, closing this PR and the other. Will open a new one on this branch. Thanks and sorry, git in VS code still confuses me sometimes.

**Pull request closed without merging**
