### PR TITLE
Bunn-12.17.24-formatting-in-octave

### PR DESCRIPTION
**Pull request by jbunn3**
I wanted to find a later place in the text where it made sense to introduce this. Suggestions are welcome.

### CODE REVIEW

**Comment by jbunn3** [comment]
The commentary code 
```
<commentary component="instructor">
  <title>Instructor Note</title>
  <p>Your note goes here.</p>
</commentary>
```
doesn't seem to be working.

**Comment by siwelwerd** [comment]
You have it within an activity right now, which may not be allowed.  Try moving it outside the activity

**Comment by jbunn3** [comment]
> You have it within an activity right now, which may not be allowed. Try moving it outside the activity

I was wondering if that was the culprit.

**Comment by siwelwerd** [comment]
Actually looking again, it's within a `<p>` as well which is almost certainly bad

**Comment by jbunn3** [comment]
> Actually looking again, it's within a `<p>` as well which is almost certainly bad

I fixed that, but all my efforts to move it around doesn't seem to fix it.

**Comment by siwelwerd** [comment]
Style guide has been updated with code that should work for the instructor note

**Comment by jbunn3** [comment]
@StevenClontz Can you take a look at this? I'm not sure why an old branch of mine got involved in this PR? Did I do something wrong?

**Comment by StevenClontz** [comment]
This was accidentally branched off fof `bunn-11.8.24-fix-sq7`, not `main`, which is why an approval wasn't necessary before the Merge button was available. I think #490 will fix this.

**Pull request merged**
