### PR TITLE
Precaclulus FN3 Checkit

### PR DESCRIPTION
**Pull request by siwelwerd**
Eventually will close https://github.com/TeamBasedInquiryLearning/library/issues/169

### CODE REVIEW

**Comment by StevenClontz** [comment]
image

Are our criterial exclusive? This generated example has more x-intercepts than those requested.

**Review by StevenClontz — CHANGES_REQUESTED** [review]
We need to find a way to avoid requiring extra x-intercepts.

**Comment by siwelwerd** [comment]
>Are our criterial exclusive? This generated example has more x-intercepts than those requested

They were supposed to be... I'll have to look when I'm back home Friday.

**Comment by StevenClontz** [comment]
Here's a stab using line segments.

https://sagecell.sagemath.org/?z=eJy1U8GOmzAUvEfKP1gRB7yBCNhoG0Xa26pVpR5y6I1FK0TMxhLYCJMWusq_9z0Ci0PYJJumXMB4Zt7zjF-pyCNRYZolzMxD8cpMz6GWe0_Ho1LNlMwLEz65KFgesax44WLNSqC4U-8O8Os95wEwMo4VK2CrVH4PH6AY7Pil3aBimZOScAFg2KzqJqAWW5sHvbiW61LLoxbJ2S-WK_b4M98yWjOmoOcE7ecQ23YdyzlF7w5QKd92g6kL-OBC9bY3ehq0Vz7RxRBtT-oKjEdxwrOXjcz5HymKMAG_oo3kETN9FLO-holiASYVkx50OR4ReErNY98uDxKge0ilZk2HZlcT1gWPLqjYApetGAZuV3WhCgtVGPV4lBX1jonXJEB7eEBrEEdQY9s9xrAC3Lc8zDY8UtgRgoQG8mhTa4U-ZokszIQLZkIFXyzF1AvoMevLMSmTcF9rlncnas5qVqZcYItO0CzDEpcY5XikNvK3uao9ynLkxpMnmYZQQ8bEMN9q3s7Ct-sFO2rMJqeiaTWMyrDfJ4eEBTHesCnXs_vztDMmtMctNa7SyNCIQeCeN-sHjftBcrrsD4nRw-F5Gnaii0NNT9McIHPB023asec9OLQxdLO0bnTR7yLKWai4eCVS9MxGr8nzc7TNSP1_3vxfYAZ6SQYVPtB_Ysf6XqMz7-kvDkJuC_TEB9y42krM4XZWDh31llYORXW5lZrwmQG5fjq8_zAc80PNegA_MR2Lm0eqR6db7jqD1_eKUJ1zoTpXz8cn3ewPyL-5OXTW27p5agTPufkXsIvs7g==&lang=sage&interacts=eJyLjgUAARUAuQ==

image

The lagrange_polynomial stuff seems slow. `spline` is faster, but it has the same problem that you need to be very careful that you don't dip above or below the endpoints. So I just used line segments, which seems to be building much faster. (thought about using some trig curves, but decided it wasn't worth the effort).

**Comment by siwelwerd** [comment]
Had a small error in the flipping logic where the third extremum wasn't getting flipped.

I agree line segments should build faster, but I think students are probably expecting smooth(ish) things.  The request in #169 was for polynomial, so I was trying to make it as polynomial as I could (i.e. piecewise polynomial with as few pieces as I could manage).

**Pull request closed without merging**
