### PR TITLE
CheckIt: add flag to preview all 1000 seeds

### LINKED ISSUE #265: CheckIt preview outcome - more options
See https://github.com/TeamBasedInquiryLearning/library/issues/258#issuecomment-2310617797

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes #265

### CODE REVIEW

**Comment by StevenClontz** [comment]
Run with `--all` to get 1000 instead of 20 seeds

**Comment by siwelwerd** [comment]
I think maybe python is eating the flag, when I run `python3 scripts/preview_outcome.py precalculus EL3 --all` I just get 20 still

**Comment by StevenClontz** [comment]
It generates all 1000, but the web app only shows 20 (just like in the live version, the other seeds only show up in LMS export and Assessment builder)

**Comment by StevenClontz** [comment]
To confirm, check out `bank.json` to make sure it's 50x bigger

**Review by siwelwerd — APPROVED** [review]

**Comment by siwelwerd** [comment]
Added a commit above to display to the user how many are being generated.

**Comment by Dadoujo** [comment]
I need a new code for the Id Samsung

**Pull request merged**
