### PR TITLE
precal EQ6 checkit

### PR DESCRIPTION
**Pull request by StevenClontz**
Closes https://github.com/TeamBasedInquiryLearning/precalculus/issues/324

### CODE REVIEW

**Comment by StevenClontz** [comment]
I'm trying to implement the form `(x+6)/(x+2) - 1 = (x+5)/(x+7)`, which simplifies to `(x+6)(x-3)=0`. However, I don't see any clear way to rig this algorithmically. Any ideas from folks used to constructing these?

**Comment by StevenClontz** [comment]
@siwelwerd @AbbyANoble any ideas?

**Comment by StevenClontz** [comment]
I chucked this out to the internet: https://math.stackexchange.com/questions/4950430/generating-a-rational-equation-with-nice-solutions

**Comment by StevenClontz** [comment]
Potential solution: 
image

**Comment by StevenClontz** [comment]
image

**Review by siwelwerd — APPROVED** [review]

**Pull request merged**
