### PR TITLE
Modified Defn 8.3.12 for clarity and added a remark.

### PR DESCRIPTION
**Pull request by jbunn3**
For #372, This change clarifies the definition of a series and helps the careful reader distinguish between a series and its sum (limit).

### CODE REVIEW

**Comment by StevenClontz** [comment]
Defining a series as a pair of a sequence and its partial sum sequence doesn't click with me as a formalization: the latter is calculated from the former, so there's a redundancy that violates DRY (Don't Repeat Yourself).

But what if we say that a series is a *function* that maps a sequence to its partial sum sequence? I'll make a competing PR for discussion to elaborate on this.

**Comment by siwelwerd** [comment]
>But what if we say that a series is a function that maps a sequence to its partial sum sequence?

I am wondering if getting this exactly precisely right in the main text is going to help our students, or if it belongs in an `<aside>` so as not to distract them from what we want them to learn.  In particular I worry that introducing a function to this definition is extra cognitive load.

**Comment by StevenClontz** [comment]
The function idea didn't survive the drafting I did at #377. But you hit the nail on the head with this cognitive load concern: I don't think 99% of students are going to appreciate a model of a series that's a pair of sequences. I ended up saying that a series *is* a partial sum sequence.

**Comment by jbunn3** [comment]
I agree with your thoughts that the cognitive load might not be right for the students. However, I am generally a fan of "planting a seed" that may help down the line, even if it doesn't make sense at the time. I say this since this is how I learned series as a student, and I didn't understand at that time either. However, later down the road, it made sense to me.

**Comment by StevenClontz** [comment]
What value does having a series be a tuple of sequences have in contrast with just being the partial sum sequence?

**Comment by StevenClontz** [comment]
Ah, I see your comment at #377, so I've marked it as ready for review, and it will close this PR once it is complete. Please suggest any improvements there. Thanks @jbunn3!

**Comment by jbunn3** [comment]
> What value does having a series be a tuple of sequences have in contrast with just being the partial sum sequence?
I think it's mostly preference. I like the nature of thinking of them both back and forth. Yes, you can think of a partial sum sequence as a property of a sequence, but you can also think of the generating sequence as a property of a given partial sum sequence (by looking at the difference of consecutive elements).

**Pull request closed without merging**
