### PR TITLE
Adjust EV6 spanning set

### PR DESCRIPTION
**Pull request by StevenClontz**
Grading some EV6, and I don't like the examples of three vectors spanning dimension two: I'd rather each problem have a bit more meat to it.

Likewise edited to ensure the vectors don't span all of R^4, though I've yet to have any student tell me that {e_1,e_2,e_3,e_4} is a basis in that case.

### CODE REVIEW

**Comment by StevenClontz** [comment]
(Thanks for the tags Drew.)

Jordan I don't have the CheckIt previewing live here, but if you trust me on the code, I'm looking for a content review of changing every https://tbil.org/preview/linear-algebra/exercises/#/bank/EV6/1/ to have either 4 or 5 vectors, and the solution to always be either dimension 2 or 3.

**Comment by siwelwerd** [comment]
Instructions for previewing Checkit problems reside [in our Wiki](https://github.com/TeamBasedInquiryLearning/library/wiki/CheckIt-Authoring)

And FWIW I eyeballed the code and it looks fine, but @jkostiuk can look at the outputted problems and verify.

**Review by jkostiuk — APPROVED** [review]
this looks good to me. Thanks @siwelwerd for the CheckIt info--I was able to follow the instructions and click a few exercises. 

@StevenClontz once this is merged, will it update the public-facing CheckIt bank?

**Comment by StevenClontz** [comment]
It will update https://tbil.org/preview/linear-algebra/exercises/#/bank/EV6/1/ but not the 2024 edition.

**Pull request merged**
