### PR TITLE
Update RAT-SQ.tex

### LINKED ISSUE #40: RAT for Module SQ and Readiness Assurance List
The [RAT for Module SQ ](RATs/RAT-SQ.tex) contains two problems (5 and 6) which ask students to determine if a given sequence is bounded, increasing, decreasing, but this skill is not listed on the [Readiness Assurance](https://teambasedinquirylearning.github.io/calculus/2023/SQ.html#SQ-readiness) list at the start of the chapter. Meanwhile, "evaluate improper integrals" is listed on the Readiness Assurance list, but the RAT contains no questions affiliated with that topic. I replacing these questions with something along the lines of [Activity 5.8.11](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#activity-352) 
would be a good review before students move toward the Integral Test.

The [Readiness Assurance](https://teambasedinquirylearning.github.io/calculus/2023/SQ.html#SQ-readiness) list of tasks could be updated to include a link back to [Section 5.8: Improper integrals (TI8)](https://teambasedinquirylearning.github.io/calculus/2023/TI8.html#TI8) under list item c. Adding to the bulleted list under (a), a link back to [Section 3.9: Limits and Derivatives (AD9)](https://teambasedinquirylearning.github.io/calculus/2023/AD9.html#AD9) 
would be appropriate, as well as [Section 1.5: Limits with infinite inputs (LT5)](https://teambasedinquirylearning.github.io/calculus/2023/LT5.html#LT5).

### PR DESCRIPTION
**Pull request by fragandi**
added comments for to-do

Closes #40

### CODE REVIEW

**Comment by fragandi** [comment]
I had troubles previewing the edits, but should be a minor issue, as you check this PR see if you can fix it!

**Comment by siwelwerd** [comment]
Sorry for the commit mess, learned about the --squash flag too late.  All of that was just merging in main so that things build with the new PreTeXt version.

**Comment by fragandi** [comment]
Ok! If you are happy with this you can close issue #40

**Comment by siwelwerd** [comment]
See #531, right now any changes to the readiness.ptx page are going to break the quick build.

**Comment by siwelwerd** [comment]
> Ok! If you are happy with this you can close issue #40

FYI the best workflow is to add the text `closes #40` into the first message of the PR (I have edited it to do this), then Github will automatically close the issue when this is merged.

**Review by siwelwerd — APPROVED** [review]

**Pull request merged**
